---
apiVersion: v1
kind: Pod
metadata:
  name: addon-operator
spec:
  containers:
  - name: addon-operator
    image: registry.mycompany.com/addon-operator:module-sysctl-tuner
    imagePullPolicy: Always
  serviceAccountName: addon-operator-acc
